# Docker compose config
#
# Included services: postgres, pgadmin4

version: "3.5"

services:
  app_flask: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5001:5000"
    depends_on:
      - "postgres-db"
    networks:
      - postgres

  postgres-db:
    container_name: postgres-db
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - twis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
  twis_data:
  pgadmin4:
