# Docker compose config
#
# Included services: postgres, pgadmin4

version: "3.5"

services:
  postgres:
    container_name: python-training-postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - twis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin4:
    container_name: python-training-pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin4:/var/lib/pgadmin
    ports:
      - "5002:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  twis_data:
  pgadmin4:
